apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-air
  labels:
    app: contoso-air
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: contoso-air
  template:
    metadata:
      labels:
        app: contoso-air
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - contoso-air
              topologyKey: kubernetes.io/node
      containers:
        - name: contoso-air
          image: nikelleacr.azurecr.io/contoso-air:2.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          lifecycle:
            preStop:
              httpGet:
                path: /healthz
                port: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
      imagePullSecrets:
        - name: acrbinding
