apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-air
  labels:
    app: contoso-air
    kubernetes.azure.com/blah: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contoso-air
  template:
    metadata:
      labels:
        app: contoso-air
    spec:
      containers:
        - name: contoso-air
          image: nikelleacr.azurecr.io/contoso-air:2.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: acrbinding
